spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/psyche_db?characterEncoding=utf-8&reWriteBatchedInserts=true
    username: ${POSTGRES_USER:psycheguard}
    password: ${POSTGRES_PASSWORD:psycheguard_dev_2025}
  sql:
    init:
      mode: never
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    show-sql: true
server:
  port: 9090

